name: 'OpenResty'
description: 'Build and install OpenResty'
inputs:
  version:
    description: 'OpenResty version (e.g. 1.19.9.1)'
    required: true
  opt:
    description: './configure [opt...]'
    default:
  cc:
    description: 'Compiler (--with-cc)'
    default:
  cc-opt:
    description: 'Compiler options (--with-cc-opt)'
    default: '-g'
  ld-opt:
    description: 'Linker options (--with-ld-opt)'
    default:
  debug:
    description: 'Enable debug build (--with-debug)'
    type: boolean
    default: false
  no-pool-patch:
    description: 'Enable no-pool patch (--with-no-pool-patch)'
    type: boolean
    default: false
  openssl-version:
    description: 'OpenSSL version (e.g. 1.1.1l)'
    default:
  openssl-opt:
    description: 'OpenSSL build options (--with-openssl-opt)'
    default:
  test-nginx:
    description: 'Install Test::Nginx'
    type: boolean
    default: true
runs:
  using: 'node12'
  main: 'src/index.js'
