name: CI

on:
  push:
    branches: main
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash

jobs:
  sanity:
    name: 'Test - sanity'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        openresty: [1.19.9.1]
        cc: [gcc-8, gcc-9]
        debug: [0, 1]
    steps:
      - run: sudo apt-get update && sudo apt-get install -y ${{ matrix.cc }}
      - uses: actions/checkout@v2
      - name: Build OpenResty
        uses: ./
        with:
          version: ${{ matrix.openresty }}
          opt: --without-stream # recent bug: cannot build stream without SSL

          with-cc: ${{ matrix.cc }}
          with-debug: ${{ matrix.debug }}
      - name: Test build
        run: |
          which openresty
          which nginx
          nginx -V
          ldd $(which nginx)

          if nginx -V 2>&1 | head -n 1 | grep -v -q -F "openresty/${{ matrix.openresty }}"; then
            echo "Nginx build version does not match matrix's (${{ matrix.openresty }})" >&2
            exit 1
          fi

          if nginx -V 2>&1 | grep -q -F "built with OpenSSL"; then
            echo "Nginx build should not have OpenSSL" >&2
            exit 1
          fi

          if [[ "${{ matrix.debug }}" == 1 ]]; then
            if ! (nginx -V 2>&1 | grep -q -F -- "--with-debug"); then
              echo "Nginx build should have --with-debug" >&2
              exit 1
            fi
          else
            if nginx -V 2>&1 | grep -q -F -- "--with-debug"; then
              echo "Nginx build should not have --with-debug" >&2
              exit 1
            fi
          fi

          cc="${{ matrix.cc }}"
          cc=${cc/-/ }
          echo $cc

          if ! (nginx -V 2>&1 | grep -q -F -- "built by $cc"); then
              echo "Nginx build not compiled by requested compiler" >&2
              exit 1
          fi
