name: CI

on:
  push:
    branches: main
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash

jobs:
  sanity:
    name: 'Test - Sanity'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        openresty: [1.19.9.1]
        cc: [gcc-8, gcc-9]
        debug: [0, 1]
        include:
          - os: macos-latest
            openresty: 1.19.9.1
            cc: clang
            no-pool: true
    steps:
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y ${{ matrix.cc }}
      - uses: actions/checkout@v2
      - name: Build OpenResty
        uses: ./
        with:
          version: ${{ matrix.openresty }}
          opt: --without-stream # recent bug: cannot build stream without SSL
          with-cc: ${{ matrix.cc }}
          with-debug: ${{ matrix.debug }}
          with-no-pool-patch: ${{ matrix.no-pool }}
      - name: Test build
        run: |
          which openresty
          which nginx
          nginx -V

          if [ -x "$(command -v ldd)" ]; then
            ldd $(which nginx)
          fi

          if nginx -V 2>&1 | head -1 | grep -v -q -F "openresty/${{ matrix.openresty }}"; then
            echo "Nginx build version does not match matrix's (${{ matrix.openresty }})" >&2
            exit 1
          fi

          if nginx -V 2>&1 | grep -q -F "built with OpenSSL"; then
            echo "Nginx build should not have OpenSSL" >&2
            exit 1
          fi

          if [[ "${{ matrix.debug }}" == 1 ]]; then
            if ! (nginx -V 2>&1 | grep -q -F -- "--with-debug"); then
              echo "Nginx build should have --with-debug" >&2
              exit 1
            fi
          else
            if nginx -V 2>&1 | grep -q -F -- "--with-debug"; then
              echo "Nginx build should not have --with-debug" >&2
              exit 1
            fi
          fi

          if [[ -n "${{ matrix.cc }}" ]]; then
            cc="${{ matrix.cc }}"
            cc=${cc/-/ }

            if ! (nginx -V 2>&1 | grep -q -F -- "built by $cc"); then
              echo "Nginx build not compiled by requested compiler" >&2
              exit 1
            fi
          fi

  openssl:
    name: 'Test - OpenSSL'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        openresty: [1.19.9.1]
        openssl: [1.0.2u, 1.1.1l]
        include:
          - os: macos-latest
            openresty: 1.19.9.1
            openssl: 1.1.1l
    steps:
      - uses: actions/checkout@v2
      - name: Build OpenResty
        uses: ./
        with:
          version: ${{ matrix.openresty }}
          with-openssl-version: ${{ matrix.openssl }}
      - name: Test build
        run: |
          which openresty
          which nginx
          nginx -V

          if [ -x "$(command -v ldd)" ]; then
            ldd $(which nginx)
          fi

          if ! (nginx -V 2>&1 | grep -q -F "built with OpenSSL"); then
            echo "Nginx have OpenSSL" >&2
            exit 1
          fi

          if ! (nginx -V 2>&1 | head -3 | grep -q -F "built with OpenSSL ${{ matrix.openssl }}"); then
            echo "Nginx built linked to wrong OpenSSL version" >&2
            exit 1
          fi
