name: CI

on:
  push:
    branches: main
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: 'OpenResty test build'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        #cc: [gcc-8, gcc-9]
        openresty: [1.19.9.1]
        #debug: [1, 0]
    steps:
      #- run: sudo apt-get update && sudo apt-get install -y ${{ matrix.cc }}
      - uses: actions/checkout@v2
      - name: Build OpenResty
        uses: ./
        with:
          version: ${{ matrix.openresty }}
          opt: --without-stream # bug: cannot build stream without SSL
          with-cc: ${{ matrix.cc }}
          with-debug: ${{ matrix.debug }}
          with-openssl-version: 1.1.1l
      - name: Test build
        run: |
          nginx -V
          openresty -V
          ldd $(which nginx)
